# Generated by Django 5.1.4 on 2025-04-28 19:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semesters_app', '0003_alter_semester_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='semesters_app.semester')),
            ],
        ),
    ]
