# Generated by Django 5.1.4 on 2025-04-28 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes_app', '0001_initial'),
        ('semesters_app', '0003_alter_semester_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='semester',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='semesters_app.semester'),
            preserve_default=False,
        ),
    ]
