# Generated by Django 5.1.4 on 2025-04-28 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes_app', '0001_initial'),
        ('departments_app', '0002_alter_subject_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='departments_app.subject'),
        ),
    ]
