# Generated by Django 5.1.4 on 2025-04-29 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes_app', '0002_class_subject'),
        ('locations_app', '0006_rename_identifier_building_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='locations_app.room'),
        ),
    ]
