# Generated by Django 5.1.4 on 2025-04-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes_app', '0003_class_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='is_suggestion',
            field=models.BooleanField(default=False),
        ),
    ]
