# Generated by Django 5.1.4 on 2025-02-19 23:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('term', models.IntegerField(choices=[(1, 'Interterm'), (2, 'Spring'), (3, 'Summer'), (4, 'Fall')])),
            ],
        ),
    ]
