# Generated by Django 5.1.4 on 2025-05-12 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesters_app', '0005_alter_semester_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['parent__uuid', 'start']},
        ),
        migrations.RemoveField(
            model_name='semester',
            name='term',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='year',
        ),
        migrations.AddField(
            model_name='semester',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_periods', to='semesters_app.semester'),
        ),
        migrations.AddField(
            model_name='semester',
            name='title',
            field=models.CharField(default='Existing semester', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semester',
            name='type',
            field=models.CharField(choices=[('year', 'Year'), ('term', 'Term'), ('subterm', 'Subterm')], default='semester title', max_length=50),
            preserve_default=False,
        ),
    ]
