# Generated by Django 5.1.4 on 2025-05-02 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='code',
            new_name='number',
        ),
    ]
