# Generated by Django 5.1.4 on 2025-05-02 21:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_alter_course_options_rename_code_course_number'),
        ('departments_app', '0003_alter_subject_department_alter_subject_name'),
        ('locations_app', '0007_alter_building_code_alter_building_name_and_more'),
        ('periods_app', '0005_alter_period_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='departments_app.subject'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('is_suggestion', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses_app.course')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='locations_app.room')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='periods_app.period')),
            ],
        ),
    ]
