# Generated by Django 5.1.4 on 2025-05-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0004_section_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='days_of_week',
            field=models.CharField(default=None, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='end_time',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='start_time',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
    ]
