# Generated by Django 5.1.4 on 2025-04-28 17:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('users_app', '0001_initial'), ('users_app', '0002_alter_user_auth_token'), ('users_app', '0003_alter_user_uuid')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('auth_token', models.CharField(max_length=255, null=True)),
                ('role', models.CharField(choices=[('DEPARTMENT_CHAIR', 'Department Chair'), ('REGISTRAR', 'Registrar'), ('PROFESSOR', 'Professor')], default='PROFESSOR', max_length=20)),
            ],
        ),
    ]
