[tool.ruff]
line-length = 100
extend-exclude = [
    "**/migrations/**.py",
    "*_app/__init__.py",
    "*_project/__init__.py",
]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "ANN202",
    "ANN401",
    "D100",
    "D203",
    "D209",
    "D212",
    "DJ001",
    "EM101",
    "TD002",
    "TD003",
]
