# Generated by Django 5.1.4 on 2025-04-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periods_app', '0003_alter_period_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='end',
            field=models.DateField(default='1970-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='period',
            name='start',
            field=models.DateField(default='1970-01-01'),
            preserve_default=False,
        ),
    ]
