# Generated by Django 5.1.4 on 2025-04-29 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periods_app', '0004_period_end_period_start'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='period',
            unique_together=set(),
        ),
    ]
