# Generated by Django 5.1.4 on 2025-05-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periods_app', '0006_alter_period_options_remove_period_term_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['parent__start', 'start']},
        ),
    ]
