# Generated by Django 5.1.4 on 2025-05-18 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periods_app', '0007_alter_period_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={},
        ),
    ]
