# Generated by Django 5.1.4 on 2025-02-24 19:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True, unique=True)),
                ('code', models.CharField(max_length=10, null=True)),
                ('available', models.BooleanField(default=True)),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations_app.building')),
            ],
        ),
    ]
