# Generated by Django 5.1.4 on 2025-02-26 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations_app', '0002_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('building', 'code', 'name')},
        ),
        migrations.AddField(
            model_name='room',
            name='default_capacity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='maximum_capacity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='locations_app.building'),
        ),
    ]
