# Generated by Django 5.1.4 on 2025-02-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations_app', '0003_alter_building_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_capacity__gte', models.F('default_capacity'))), name='maximum_capacity_must_be_greater_than_default_capacity'),
        ),
    ]
