# Generated by Django 5.1.4 on 2025-04-28 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations_app', '0005_remove_room_maximum_capacity_must_be_greater_than_default_capacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='identifier',
            new_name='code',
        ),
    ]
