# Generated by Django 5.1.4 on 2025-04-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations_app', '0006_rename_identifier_building_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
