# Generated by Django 5.1.4 on 2025-05-08 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations_app', '0008_alter_room_building'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('building', 'number', 'name')},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='code',
            new_name='number',
        ),
    ]
