# Generated by Django 5.1.4 on 2025-03-05 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes_app', '0001_initial'),
        ('semesters_app', '0003_alter_semester_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='semesters_app.semester'),
        ),
        migrations.AddField(
            model_name='change',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
