# Generated by Django 5.1.4 on 2025-05-18 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes_app', '0002_change_period_change_status'),
        ('courses_app', '0005_section_days_of_week_section_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='change',
            name='period',
        ),
        migrations.AddField(
            model_name='change',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='change',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='courses_app.section'),
        ),
        migrations.AddField(
            model_name='change',
            name='type',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], default='create', max_length=10),
            preserve_default=False,
        ),
    ]
