# Generated by Django 5.1.4 on 2025-05-18 10:18

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes_app', '0003_remove_change_period_change_data_change_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='change',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
