# Generated by Django 5.1.4 on 2025-03-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
